
var wf=localStorage.getItem('wf');
var v1= localStorage.getItem("v1");
var cod=localStorage.getItem("cod");
var n2=localStorage.getItem("n2");
var n1=localStorage.getItem("n1");
var b=localStorage.getItem("b");
var bl=localStorage.getItem("bl");
var cod=localStorage.getItem("cod");
var f1=localStorage.getItem("f1");
var f2=localStorage.getItem("f2");
var f3=localStorage.getItem("f3");
document.getElementById("t1").innerText=wf;
document.getElementById("t2").innerText=n1;
document.getElementById('t3').innerText=n1;
document.getElementById("t4").innerText=f1;
document.getElementById("t5").innerText=f2;
document.getElementById('t6').innerText=f3;
document.getElementById("t7").innerText=f1;
document.getElementById("t8").innerText=f2;
document.getElementById('t9').innerText=f3;
document.getElementById('t10').innerText=bl;
document.getElementById('t11').innerText=v1;
document.getElementById('t12').innerText=n2;
document.getElementById('t13').innerText=cod;
localStorage.removeItem('wf');
localStorage.removeItem("v1");
localStorage.removeItem("cod");
localStorage.removeItem("n2");
localStorage.removeItem("n1");
localStorage.removeItem("b");
localStorage.removeItem("bl");
localStorage.removeItem("f1");
localStorage.removeItem("f2");
localStorage.removeItem("f3");